package router

import (
	"log/slog"
	"net/http"
	"net/http/pprof" // Import pprof package

	"gostreampuller/config"
	"gostreampuller/handler"
	"gostreampuller/middleware"
	"gostreampuller/service"

	_ "gostreampuller/docs" // docs is generated by Swag CLI
	httpSwagger "github.com/swaggo/http-swagger"
)

// Router holds the HTTP multiplexer and configuration.
type Router struct {
	Mux *http.ServeMux
	cfg *config.Config
}

// New creates a new Router instance and initializes routes.
func New(cfg *config.Config) *Router {
	mux := http.NewServeMux()

	// Create services
	downloader := service.NewDownloader(cfg)

	// Create handlers
	healthHandler := handler.NewHealthHandler()
	downloadVideoHandler := handler.NewDownloadVideoHandler(downloader)
	downloadAudioHandler := handler.NewDownloadAudioHandler(downloader)
	streamVideoHandler := handler.NewStreamVideoHandler(downloader)
	streamAudioHandler := handler.NewStreamAudioHandler(downloader)
	webStreamHandler := handler.NewWebStreamHandler(downloader) // New web stream handler

	// Register routes
	mux.HandleFunc("/health", healthHandler.Handle)

	// Download routes
	mux.HandleFunc("POST /download/video", downloadVideoHandler.Handle)
	mux.HandleFunc("GET /download/video/{filename}", downloadVideoHandler.ServeDownloadedVideo)
	mux.HandleFunc("POST /download/video/info", downloadVideoHandler.GetVideoInfo)
	mux.HandleFunc("POST /download/audio", downloadAudioHandler.Handle)
	mux.HandleFunc("GET /download/audio/{filename}", downloadAudioHandler.ServeDownloadedAudio)
	mux.HandleFunc("DELETE /download/delete/{filename}", downloadVideoHandler.DeleteDownloadedFile) // Re-use for any file deletion
	mux.HandleFunc("GET /download/list", downloadVideoHandler.ListDownloadedFiles) // Re-use for any file listing

	// Stream routes
	mux.HandleFunc("POST /stream/video", streamVideoHandler.Handle)
	mux.HandleFunc("POST /stream/audio", streamAudioHandler.Handle)

	// Web Stream routes
	mux.HandleFunc("GET /web/stream", webStreamHandler.ServeStreamPage)
	mux.HandleFunc("POST /web/stream", webStreamHandler.HandleWebStream)
	mux.HandleFunc("GET /web/stream/play", webStreamHandler.PlayWebStream) // Endpoint for the video player source

	// Serve Swagger UI
	mux.HandleFunc("/swagger/", httpSwagger.WrapHandler)
	slog.Info("Swagger UI available at /swagger/index.html")

	// Enable pprof endpoints if debug mode is enabled
	if cfg.DebugMode {
		slog.Info("Debug mode enabled: Registering pprof endpoints")
		mux.HandleFunc("/debug/pprof/", pprof.Index)
		mux.HandleFunc("/debug/pprof/cmdline", pprof.Cmdline)
		mux.HandleFunc("/debug/pprof/profile", pprof.Profile)
		mux.HandleFunc("/debug/pprof/symbol", pprof.Symbol)
		mux.HandleFunc("/debug/pprof/trace", pprof.Trace)
		// Alternatively, for more fine-grained control:
		// mux.Handle("/debug/pprof/goroutine", pprof.Handler("goroutine"))
	}

	return &Router{
		Mux: mux,
		cfg: cfg,
	}
}

// Handler returns the http.Handler with middleware applied.
func (r *Router) Handler() http.Handler {
	// Wrap the ServeMux with the logging middleware
	return middleware.LoggingMiddleware(r.cfg)(r.Mux)
}
