apiVersion: apps/v1
kind: Deployment
metadata:
  name: gostreampuller
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gostreampuller
  template:
    metadata:
      labels:
        app: gostreampuller
    spec:
      containers:
        - image: mohammaddocker/gostreampuller
          name: gostreampuller
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 800m
              memory: 500Mi
          env:  
            - name: PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: managed-gostreampuller-secret