apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-go-api-template

resources:
- deployment.yml
- service.yml

images:
- name: mohammaddocker/home-go-api-template
  newTag: 0.4.0
