apiVersion: v1
kind: Service
metadata:
  name: home-go-api-template-service
spec:
  selector:
    app: home-go-api-template # Match labels from the deployments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-certificate
spec:
  commonName: api.bnei.dev
  secretName: api-certificate-secret
  dnsNames:
    - "api.bnei.dev"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-go-api-template
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: Host(`api.bnei.dev`) && PathPrefix(`/home-go-api-template`)
      services:
        - kind: Service
          name: home-go-api-template-service
          namespace: home-go-api-template
          port: 80
      middlewares:
        - name: path-stripper
          namespace: home-go-api-template
  tls:
    secretName: api-certificate-secret

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: path-stripper
spec:
  stripPrefix:
    prefixes:
      - /home-go-api-template