basePath: /
definitions:
  handler.DownloadAudioRequest:
    properties:
      bitrate:
        type: string
      codec:
        type: string
      outputFormat:
        type: string
      url:
        type: string
    type: object
  handler.DownloadAudioResponse:
    properties:
      filePath:
        type: string
      message:
        type: string
      videoInfo:
        allOf:
        - $ref: '#/definitions/service.VideoInfo'
        description: Re-use VideoInfo for audio metadata
    type: object
  handler.DownloadVideoRequest:
    properties:
      codec:
        type: string
      format:
        type: string
      resolution:
        type: string
      url:
        type: string
    type: object
  handler.DownloadVideoResponse:
    properties:
      filePath:
        type: string
      message:
        type: string
      videoInfo:
        $ref: '#/definitions/service.VideoInfo'
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  handler.FileInfo:
    properties:
      modTime:
        type: string
      name:
        type: string
      size:
        type: integer
    type: object
  handler.GetVideoInfoRequest:
    properties:
      url:
        type: string
    type: object
  handler.GetVideoInfoResponse:
    properties:
      message:
        type: string
      videoInfo:
        $ref: '#/definitions/service.VideoInfo'
    type: object
  handler.ListDownloadedFilesResponse:
    properties:
      files:
        items:
          $ref: '#/definitions/handler.FileInfo'
        type: array
      message:
        type: string
    type: object
  handler.StreamAudioRequest:
    properties:
      bitrate:
        type: string
      codec:
        type: string
      outputFormat:
        type: string
      url:
        type: string
    type: object
  handler.StreamVideoRequest:
    properties:
      codec:
        type: string
      format:
        type: string
      resolution:
        type: string
      url:
        type: string
    type: object
  handler.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  service.VideoInfo:
    properties:
      duration:
        description: in seconds
        type: integer
      ext:
        type: string
      id:
        type: string
      original_url:
        type: string
      thumbnail:
        description: URL to thumbnail
        type: string
      title:
        type: string
      upload_date:
        description: YYYYMMDD
        type: string
      uploader:
        type: string
    type: object
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: A lightweight, containerized REST API service that provides video and
    audio download and streaming functionalities using yt-dlp and ffmpeg.
  title: GoStreamPuller API
  version: "1.0"
paths:
  /download/audio:
    post:
      consumes:
      - application/json
      description: Downloads an audio file from a given URL to the server's download
        directory.
      parameters:
      - description: Audio download request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.DownloadAudioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Audio downloaded successfully
          schema:
            $ref: '#/definitions/handler.DownloadAudioResponse'
        "400":
          description: Invalid request payload or missing URL
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error during audio download
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Download an audio file
      tags:
      - download
  /download/audio/{filename}:
    get:
      description: Serves an audio file from the server's download directory given
        its filename.
      parameters:
      - description: Filename of the audio to serve
        in: path
        name: filename
        required: true
        type: string
      produces:
      - audio/mpeg
      responses:
        "200":
          description: Successfully served audio file
          schema:
            type: file
        "400":
          description: Missing filename
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Serve a downloaded audio file
      tags:
      - download
  /download/delete/{filename}:
    delete:
      description: Deletes a file from the server's download directory given its filename.
      parameters:
      - description: Filename of the file to delete
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: File deleted successfully
          schema:
            $ref: '#/definitions/handler.SuccessResponse'
        "400":
          description: Missing filename
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error during file deletion
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Delete a downloaded file
      tags:
      - download
  /download/list:
    get:
      description: Lists all files present in the server's configured download directory.
      produces:
      - application/json
      responses:
        "200":
          description: Successfully listed downloaded files
          schema:
            $ref: '#/definitions/handler.ListDownloadedFilesResponse'
        "500":
          description: Internal server error during file listing
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: List downloaded files
      tags:
      - download
  /download/video:
    post:
      consumes:
      - application/json
      description: Downloads a video from a given URL to the server's download directory.
      parameters:
      - description: Video download request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.DownloadVideoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Video downloaded successfully
          schema:
            $ref: '#/definitions/handler.DownloadVideoResponse'
        "400":
          description: Invalid request payload or missing URL
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error during video download
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Download a video
      tags:
      - download
  /download/video/{filename}:
    get:
      description: Serves a video file from the server's download directory given
        its filename.
      parameters:
      - description: Filename of the video to serve
        in: path
        name: filename
        required: true
        type: string
      produces:
      - video/mp4
      responses:
        "200":
          description: Successfully served video file
          schema:
            type: file
        "400":
          description: Missing filename
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Serve a downloaded video file
      tags:
      - download
  /download/video/info:
    post:
      consumes:
      - application/json
      description: Retrieves metadata for a video from a given URL without downloading
        the file.
      parameters:
      - description: Video info request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.GetVideoInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Video information retrieved successfully
          schema:
            $ref: '#/definitions/handler.GetVideoInfoResponse'
        "400":
          description: Invalid request payload or missing URL
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error during video info retrieval
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get video information
      tags:
      - download
  /stream/audio:
    post:
      consumes:
      - application/json
      description: Streams an audio file directly from the source URL.
      parameters:
      - description: Audio stream request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.StreamAudioRequest'
      produces:
      - audio/mpeg
      responses:
        "200":
          description: Successfully streamed audio
          schema:
            type: file
        "400":
          description: Invalid request payload or missing URL
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error during audio streaming
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Stream an audio file
      tags:
      - stream
  /stream/video:
    post:
      consumes:
      - application/json
      description: Streams a video directly from the source URL.
      parameters:
      - description: Video stream request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.StreamVideoRequest'
      produces:
      - video/mp4
      responses:
        "200":
          description: Successfully streamed video
          schema:
            type: file
        "400":
          description: Invalid request payload or missing URL
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error during video streaming
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Stream a video
      tags:
      - stream
  /web/stream:
    get:
      description: Serves an HTML page that allows users to input a URL and stream
        video.
      produces:
      - text/html
      responses:
        "200":
          description: HTML page for video streaming
          schema:
            type: string
      summary: Serve web streaming page
      tags:
      - web
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Processes the form submission for web-based video streaming, fetches
        video info, and redirects to the stream.
      parameters:
      - description: Video URL
        in: formData
        name: url
        required: true
        type: string
      - description: Video Resolution (e.g., 720, 1080)
        in: formData
        name: resolution
        type: string
      - description: Video Codec (e.g., avc1, vp9)
        in: formData
        name: codec
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: HTML page with streamed video and info
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Handle web stream request
      tags:
      - web
  /web/stream/play:
    get:
      description: Streams the video content directly to the browser based on query
        parameters.
      parameters:
      - description: Video URL
        in: query
        name: url
        required: true
        type: string
      - description: Video Resolution (e.g., 720, 1080)
        in: query
        name: resolution
        type: string
      - description: Video Codec (e.g., avc1, vp9)
        in: query
        name: codec
        type: string
      produces:
      - video/mp4
      responses:
        "200":
          description: Successfully streamed video
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Play web stream
      tags:
      - web
schemes:
- http
swagger: "2.0"
